### PR TITLE
v1.0.2 update (for real this time)

### PR DESCRIPTION
**Pull request by averwhy**
remind me to type this out later

### CODE REVIEW

**Comment by averwhy** [comment]
wow. I fucked this up AGAIN. github likes to automatically set the desination to merge, to the repo i forked from, instead of my fork... got dammit

**Comment by DedaDev** [comment]
anyway, create `python` branch.

**Comment by averwhy** [comment]
on your repo? or mine

**Comment by DedaDev** [comment]
I just made one. just request a pull there.

**Pull request closed without merging**
